apiRules:
- include:
    uidRegex: ^nickmaltbie\.ProjectCoda
    type: Namespace
- include:
    uidRegex: ^nickmaltbie\.ProjectCoda\.*
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace